add_ons:
    apt_packages:
        - pandoc
        - poppler-utils
        - texlive-full

language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"

install:
    - pip3 install -r requirements.txt

script:
    - cd zombies && make
