add_ons:
    apt_packages:
        - pandoc
        - texlive
        - texlive-latex-base

language: python

python:
    - "3.6"
    # - "3.8"

install:
    - pip3 install -r requirements.txt

script:
    - cd zombies && make
